### ISSUE TITLE
Multi instance not working?

### ISSUE THREAD

**Issue by joshuahiskraken** [joshuahiskraken/csvscripts#1]
Tried to enact two instances of 'readCSV' 
one for each csv file, so I could maybe make a promise.all to match then use something like .filter and pull the entries that matched
but it output is just the same thing twice. Like once the file is loaded in the first instance, it remains in .getData(); or something. Am I understanding this correctly, or did I mess up somewhere?
 
I tried using the same import 'csvFIle' and making a completely new import. same result. does this have something to do with it being Sync vs Async?

`const csvFile = require('./readCSV');`  
`const csvFile2 = require('./readCSV');`

`const csv2 = new csvFile2('./a.csv');`
`const info2 = csv2.getData();`
`var mapped2 = info2[0]['Order ID'];`
`console.log(mapped2)`

`const csv = new csvFile('./b.csv');`
`const info = csv.getData();`
`var mapped = info[0]['Order ID'];`
`console.log(mapped);`

root@Hekmatyr:/mnt/c/Users/never/project/!csvscripts# node app
{ 'Order ID': '108026126', '': '' }
{ 'Order ID': '108026126', '': '' }`

**Comment by JimSigler** [comment]
You can try using the promise.all with filter.  That would be a cleaner way of filtering the data rather than iterating through all of it.

**Comment by JimSigler** [comment]
sorry, I've been leaving all my comments in the code.

**Comment by joshuahiskraken** [comment]
output was a global variable thus when getData(); was called the variable would not reset with the second loaded .csv
Moving output array inside scope of getData(); solved the issue.  

`const fs    = require('fs');`
 `//let output = [];`
`function ReadCSV(fileName, headers){`
`   return {`
  	`_fileName: fileName,`
  	`_headers: headers,`
  	`getHeaders,`
  	`getData`
 ` }`
`}`

`module.exports = ReadCSV;`

`function getData(){`
` ** let output = [];`
